### ISSUE TITLE
Todos and Ideas

### ISSUE THREAD

**Issue by kriswep** [kriswep/tpp#1]
# Todos for v1
- [ ] Make `cards` route default, reomve others
- [ ] Show errors on connection / room creation
- [ ] Show connection loss error
- [ ] Show connected persons

## Ideas for later
- Save name for next session
- Save room for next sesstion
- Make rooms linkable
